# Generated by Django 3.2.19 on 2023-06-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0002_appointment_rescheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reschedule_count',
            field=models.IntegerField(default=0),
        ),
    ]
