# Generated by Django 3.2.19 on 2023-06-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0003_appointment_reschedule_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='reschedule_count',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='rescheduled',
        ),
        migrations.AddField(
            model_name='appointment',
            name='reschedule_date',
            field=models.DateField(null=True),
        ),
    ]
