# Generated by Django 3.2.19 on 2023-06-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0004_auto_20230625_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='subject',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
