# Generated by Django 3.2.19 on 2023-10-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0007_appointment_is_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_seen',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reschedule_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
