# Generated by Django 3.2.19 on 2023-10-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0008_auto_20231002_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reschedule_date',
            field=models.DateField(null=True),
        ),
    ]
