# Generated by Django 3.2.19 on 2023-10-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_doc', '0013_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
